name: Render Deployment

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      